### ISSUE TITLE
bhyve vnc broken on 20181206T012147Z ?

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#816]
[root@boron ~]# vmadm get eceec5eb-22c7-e65b-fd6b-81ebdb36406b | json vnc_port
5901
[root@boron ~]# vmadm get eceec5eb-22c7-e65b-fd6b-81ebdb36406b | json bootrom
uefi
[root@boron ~]# netstat -na | grep LISTEN
127.0.0.1.4999             *.*                0      0 1048576      0 LISTEN
      *.111                *.*                0      0 1048576      0 LISTEN
      *.111                *.*                0      0 1048576      0 LISTEN
      *.22                 *.*                0      0 1048576      0 LISTEN
127.0.0.1.9090             *.*                0      0 1048576      0 LISTEN
127.0.0.1.8080             *.*                0      0 1048576      0 LISTEN
127.0.0.1.25               *.*                0      0 1048576      0 LISTEN
127.0.0.1.587              *.*                0      0 1048576      0 LISTEN
10.23.40.211.5091          *.*                0      0 1048576      0 LISTEN
      *.111                             *.*                             0      0 1048576      0 LISTEN
      *.22                              *.*                             0      0 1048576      0 LISTEN
::1.25                                  *.*                             0      0 1048576      0 LISTEN
[root@boron ~]# uname -a
SunOS boron 5.11 joyent_20181206T012147Z i86pc i386 i86pc****

**Comment by sjorge** [comment]
@mgerdts ping

**Comment by sjorge** [comment]
```
[root@boron ~]# vmadm list
UUID                                  TYPE  RAM      STATE             ALIAS
a316a659-f1d8-c131-d7c3-fc5ad398bc1e  BHYV  1024     running           -
cde351a9-e23d-6856-e268-fff10fe603dc  BHYV  4096     stopped           fermion
eceec5eb-22c7-e65b-fd6b-81ebdb36406b  BHYV  4096     running           wino
f191e2f4-d8ef-cbfc-af34-cdf457af50f7  BHYV  4096     stopped           inflaton
f3e59c75-51a8-e862-b7e1-8e3265fd555c  BHYV  4096     running           hydrogen
```

The VM was running at the time, forgot that bit in the first post.

**Comment by pfmooney** [comment]
Looks like vmadmd may not have detected the instance coming online (and plumbing the appropriate socket forwarding)?

**Comment by sjorge** [comment]
My other VM does not have it either after booting it. Its at 5902 instead.

**Comment by sjorge** [comment]
Manually forwarding to the socket doesn't work either,

```socat -d -d TCP4-LISTEN:5901,fork UNIX-CONNECT:/zones/eceec5eb-22c7-e65b-fd6b-81ebdb36406b/root/tmp/vm.vnc```

vnc clients give 'unknown message' popup.

**Comment by sjorge** [comment]
Ok so attaching socat to the unix socket was a bad idea, when restarting the VM it is not stuck in the down state.

**Comment by sjorge** [comment]
```
pmooney
sjorge: kill the socat process?
[18:08:17]
sjorge
That was dead before I tried to stop the vm
[18:08:34]
socat does seem to work for a few second, until the viewr exits
[18:10:00]
pmooney
which viewer are you using?
[18:11:17]
when I was doing windows testing under bhyve, I found it to be rather picky
[18:11:32]
sjorge
Tried both the macOS one and the one from pkgsrc... so tigervnc?
[18:11:49]
vncviewer-4.1.3      Viewer for remote X and Win32 VNC servers
[18:12:02]
That one
[18:12:04]
Copyright (C) 2002-2008 RealVNC Ltd.
[18:12:27]
pmooney
mm
[18:12:30]
tiger is what I've used, I think
[18:12:38]
sjorge
Well problem is to fold I guess, 1st nothing is listening, if I do it myself with socat the client is not happy
[18:12:56]
There is also tightvncviewer in pkgsrc, let me switch... I thought i had 'tiget' vnc from pkgsrc but it was probably tightvnc
[18:13:36]
*tiger
[18:13:40]
Yep! Tightvncviewer works!
```

From on IRC, using socat + tightvncviewer I can connect, I had installed the plain vncviewer  (RealVNC) package from pkgsrc which does not work.

**Comment by sjorge** [comment]
```
{"name":"vmadmd","hostname":"boron","pid":6086,"level":20,"msg":"calling loadVM(eceec5eb-22c7-e65b-fd6b-81ebdb36406b)","time":"2018-12-07T17:05:06.133Z","v":0}
{"name":"vmadmd","hostname":"boron","pid":6086,"level":20,"msg":"LOADING {\"zonename\":\"eceec5eb-22c7-e65b-fd6b-81ebdb36406b\",\"autoboot\":false,\"brand\":\"bhyve\",\"v\":1,\"create_timestamp\":\"2018-09-03T17:02:42.132Z\",\"max_physical_memory\":5376,\"max_swap\":5376,\"ram\":4096,\"disks\":[{\"path\":\"/dev/zvol/rdsk/zones/eceec5eb-22c7-e65b-fd6b-81ebdb36406b/disk0\",\"boot\":true,\"model\":\"virtio\",\"media\":\"disk\",\"pci_slot\":\"0:4:0\",\"zfs_filesystem\":\"zones/eceec5eb-22c7-e65b-fd6b-81ebdb36406b/disk0\",\"zpool\":\"zones\",\"size\":30720,\"compression\":\"lz4\",\"refreservation\":31683,\"block_size\":8192}],\"nics\":[{\"interface\":\"net0\",\"mac\":\"82:fc:0c:c2:e4:6f\",\"vlan_id\":10,\"nic_tag\":\"trunk\",\"ip\":\"dhcp\",\"ips\":[\"dhcp\",\"addrconf\"],\"model\":\"virtio\",\"primary\":true}],\"vnc_port\":5901,\"uuid\":\"eceec5eb-22c7-e65b-fd6b-81ebdb36406b\",\"zone_state\":\"installed\",\"zonepath\":\"/zones/eceec5eb-22c7-e65b-fd6b-81ebdb36406b\",\"state\":\"stopped\",\"customer_metadata\":{},\"internal_metadata\":{},\"zfs_filesystem\":\"zones/eceec5eb-22c7-e65b-fd6b-81ebdb36406b\",\"zpool\":\"zones\"}","time":"2018-12-07T17:05:06.133Z","v":0}
{"name":"vmadmd","hostname":"boron","pid":6086,"level":20,"msg":"VM eceec5eb-22c7-e65b-fd6b-81ebdb36406b state: stopped","time":"2018-12-07T17:05:06.133Z","v":0}
{"name":"vmadmd","hostname":"boron","pid":6086,"level":20,"msg":"skipping vnc setup for non-running VM eceec5eb-22c7-e65b-fd6b-81ebdb36406b","time":"2018-12-07T17:05:06.133Z","v":0}
```

This is interesting! I stopped the vm (vmadm stop), waited for it to be stopped and started it again... this is in vmadmd's log...

**Comment by sjorge** [comment]
Here is a repeatable test of sorts:

```
[root@boron ~]# vmadm list
UUID                                  TYPE  RAM      STATE             ALIAS
cde351a9-e23d-6856-e268-fff10fe603dc  BHYV  4096     stopped           fermion
eceec5eb-22c7-e65b-fd6b-81ebdb36406b  BHYV  4096     running           wino
f191e2f4-d8ef-cbfc-af34-cdf457af50f7  BHYV  4096     stopped           inflaton
f3e59c75-51a8-e862-b7e1-8e3265fd555c  BHYV  4096     running           hydrogen
[root@boron ~]# vmadm get eceec5eb-22c7-e65b-fd6b-81ebdb36406b | json vnc_port
5901
[root@boron ~]# netstat -na | grep 5901
10.23.40.211.5901          *.*                0      0 1048576      0 LISTEN
[root@boron ~]# vmadm stop eceec5eb-22c7-e65b-fd6b-81ebdb36406b
Successfully completed stop for VM eceec5eb-22c7-e65b-fd6b-81ebdb36406b
[root@boron ~]# netstat -na | grep 5901
10.23.40.211.5901          *.*                0      0 1048576      0 LISTEN
[root@boron ~]# vmadm list
UUID                                  TYPE  RAM      STATE             ALIAS
cde351a9-e23d-6856-e268-fff10fe603dc  BHYV  4096     stopped           fermion
eceec5eb-22c7-e65b-fd6b-81ebdb36406b  BHYV  4096     stopped           wino
f191e2f4-d8ef-cbfc-af34-cdf457af50f7  BHYV  4096     stopped           inflaton
f3e59c75-51a8-e862-b7e1-8e3265fd555c  BHYV  4096     running           hydrogen
[root@boron ~]# svcadm restart vmadmd
[root@boron ~]# netstat -na | grep 5901
[root@boron ~]#
```

The reverse also works, start the vm, then restart vmadmd makes the tcp socket show up.

**Comment by bahamas10** [comment]
@sjorge I followed your steps and am not seeing this behavior.

Using the following VM payload:

``` json
{
  "alias": "test-bhyve",
  "brand": "bhyve",
  "do_not_inventory": true,
  "autoboot": false,
  "ram": 1024,
  "vnc_port": 5901,
  "vcpus": 1,
  "disks": [
    {
      "image_uuid": "462d1d03-8457-e134-a408-cf9ea2b9be96",
      "boot": true,
      "model": "virtio"
    }
  ]
}
```

I create the VM and verify no vnc connection exists:

```
[root@headnode (coal) ~]# vmadm create -f /var/tmp/daves-tools/bhyve.json
Successfully created VM ab76575d-db4a-4347-df81-a39c60abc3c8
[root@headnode (coal) ~]# netstat -na | grep 5901
[root@headnode (coal) ~]#
```

I start the VM and verify the connection exists:

```
[root@headnode (coal) ~]# vmadm start ab76575d-db4a-4347-df81-a39c60abc3c8 
Successfully started VM ab76575d-db4a-4347-df81-a39c60abc3c8
[root@headnode (coal) ~]# netstat -na | grep 5901
10.99.99.7.5901            *.*                0      0 1048576      0 LISTEN
```

And finally I stop the VM and verify the connection is gone:

```
[root@headnode (coal) ~]# vmadm stop ab76575d-db4a-4347-df81-a39c60abc3c8 
Successfully completed stop for VM ab76575d-db4a-4347-df81-a39c60abc3c8
[root@headnode (coal) ~]# netstat -na | grep 5901
[root@headnode (coal) ~]# 
```

I waited about 1-2 seconds after running each `vmadm` command to run the follow up `netstat` command.

`vmadmd` uses `zoneevent` which uses vminfod monitoring the `zone_state` property under-the-hood.  Can you run the following command?

    # vmadm events $uuid | grep 'zone_state changed'

And, while leaving that running, issue a `vmadm stop` and then a `vmadm start` of the VM?  On my machine, I see:

`vmadm stop $uuid`

```
[18:05:29.781Z] ab76575d test-bhyve modify: zone_state changed :: "running" -> "shutting_down"
[18:05:30.799Z] ab76575d test-bhyve modify: zone_state changed :: "shutting_down" -> "down"
[18:05:30.907Z] ab76575d test-bhyve modify: zone_state changed :: "down" -> "installed"
```

`vmadm start $uuid`

```
[18:05:36.848Z] ab76575d test-bhyve modify: zone_state changed :: "installed" -> "ready"
[18:05:36.986Z] ab76575d test-bhyve modify: zone_state changed :: "ready" -> "running"
```

**Comment by bahamas10** [comment]
After talking with @pfmooney I am able to recreate this!

1. set autoboot to false on the VM in question
2. reboot the box
3. start the VM

After doing this, there is no connection created:

```
[root@headnode (coal) ~]# vmadm start ab76575d-db4a-4347-df81-a39c60abc3c8
Successfully started VM ab76575d-db4a-4347-df81-a39c60abc3c8
[root@headnode (coal) ~]# netstat -an | grep 5901
[root@headnode (coal) ~]#
```

Also, `vmadmd` generates no logs at all for the VM when it is started or stopped... it's missing something.  I'll dig into this more.

@sjorge I don't need what I asked for above - sorry about that!

**Comment by sjorge** [comment]
Ah yes! All the vm that have the issue have autonoom=false as most are build machines for omnios, FreeBSD,...

**Comment by bahamas10** [comment]
I will be passing this issue off, but here is the internal ticket filed for it with an explanation.  Basically, `vmadmd` could use some love and could be made better, and that should fix this issue indirectly: http://smartos.org/bugview/OS-7459

**Comment by matthiasg** [comment]
should bhyve vnc work ? i could not get it past a black screen. not in bios (i think that is expected) nor in uefi mode. which vnc client is usable anyway ? i tried tightvnc and ultravnc

**Comment by sjorge** [comment]
It works fine for me in UEFI mode with tight VNC viewer.

~ sjorge

**Comment by mgerdts** [comment]
I've used tightvnc before, and most commonly use chicken.  Do not force any
particular color depth, compression, etc., as the VNC server in bhyve is
pretty bare-bones.

Also, if you use `vmadm update` to change the vnc port, you may need to
`svcadm restart vmadmd` for it to recognize the change.

https://smartos.org/bugview/OS-7953

Mike

**Comment by sjorge** [comment]
So this is still an issue, for now my work around is to restart vmadmd **after** the bhyve vm has been started. It also does not clean up the listening socket if the vm is stopped... until I restart vmadmd again.

**Comment by marcheschi** [comment]
Hi I tried again today and the only way to connect to bhyve vnc port is doing a vmadmd restart.
I can connect using TigerVNC software under linux, with default settings.
I also noticed that when I try to stop the bhyve vm, it goes in a "down" state for a while until it becomes finally Stopped.
Paolo

**Comment by xtreegpt** [comment]
I am running 20201007T223416Z and ran into this issue. Running svcadm restart vmadmd worked. Once I did the restart I was able to VNC into my Bhyve VM. As stated earlier you can also check by netstat -an |grep -i listen and check for VNC ports. Mine are 59xx.
